import type { Metadata } from "next";
import "../../styles/globals.css";

import { Roboto } from "next/font/google";
import { CompanyRegisterProvider } from "@/contexts/companyRegister";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "@/components/header";
import NextAuthProvider from "@/configs/NextAuthProvider";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={roboto.className}>
        <NextAuthProvider>
          <CompanyRegisterProvider>
            <Header />
            {children}
          </CompanyRegisterProvider>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
