import type { Metadata } from "next";
import "../configs/globals.css";

import { Roboto } from "next/font/google";
import { CompanyRegisterProvider } from "@/contexts/companyRegister";
import NextAuthProvider from "./api/auth/[...nextauth]/NextauthProvider";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={roboto.className}>
        <NextAuthProvider>
          <CompanyRegisterProvider>{children}</CompanyRegisterProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
